# Clock configuration
- ros_topic_name: "clock"
  gz_topic_name: "clock"
  ros_type_name: "rosgraph_msgs/msg/Clock"
  gz_type_name: "gz.msgs.Clock"
  direction: GZ_TO_ROS
  lazy: false

#Joint state configuration
- ros_topic_name: "/joint_states"
  gz_topic_name: "/world/empty/model/delivery/joint_state"
  ros_type_name: "sensor_msgs/msg/JointState"
  gz_type_name: "gz.msgs.Model"
  direction: GZ_TO_ROS
  lazy: false

# IMU configuration
- ros_topic_name: "imu/data"
  gz_topic_name: "/imu"
  ros_type_name: "sensor_msgs/msg/Imu"
  gz_type_name: "gz.msgs.IMU"
  direction: GZ_TO_ROS
  lazy: false

# LIDAR configuration
- ros_topic_name: "scan"
  gz_topic_name: "/scan"
  ros_type_name: "sensor_msgs/msg/LaserScan"
  gz_type_name: "gz.msgs.LaserScan"
  direction: GZ_TO_ROS
  lazy: false
# Camera configuration
- ros_topic_name: "/camera/camera_info"
  gz_topic_name: "/camera/camera_info"
  ros_type_name: "sensor_msgs/msg/CameraInfo"
  gz_type_name: "gz.msgs.CameraInfo"
  direction: GZ_TO_ROS

- ros_topic_name: "/camera/image_raw"
  gz_topic_name: "/camera/image_raw"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  direction: GZ_TO_ROS

# Alternative for single pose message
- ros_topic_name: "/ground_truth_pose"
  gz_topic_name: "/model/delivery/pose "
  ros_type_name: "geometry_msgs/msg/Pose"
  gz_type_name: "gz.msgs.Pose"
  direction: GZ_TO_ROS








# # Sending velocity commands from ROS 2 to Gazebo
# - ros_topic_name: "mecanum_controller/cmd_vel"
#   gz_topic_name: "model/delivery/cmd_vel"
#   ros_type_name: "geometry_msgs/msg/TwistStamped"
#   gz_type_name: "gz.msgs.Twist"
#   direction: ROS_TO_GZ
#   lazy: false

# # Sending odometry commands from ROS 2 to Gazebo
# - ros_topic_name: "mecanum_controller/odom"
#   gz_topic_name: "model/delivery/odometry"
#   ros_type_name: "geometry_msgs/msg/TwistStamped"
#   gz_type_name: "gz.msgs.Twist"
#   direction: ROS_TO_GZ
#   lazy: false


 