# Clock configuration
- ros_topic_name: "clock"
  gz_topic_name: "clock"
  ros_type_name: "rosgraph_msgs/msg/Clock"
  gz_type_name: "gz.msgs.Clock"
  direction: GZ_TO_ROS
  lazy: false

#Joint state configuration
- ros_topic_name: "/joint_states"
  gz_topic_name: "/world/empty/model/delivery/joint_state"
  ros_type_name: "sensor_msgs/msg/JointState"
  gz_type_name: "gz.msgs.Model"
  direction: GZ_TO_ROS
  lazy: false




# Sending velocity commands from ROS 2 to Gazebo
- ros_topic_name: "mecanum_controller/cmd_vel"
  gz_topic_name: "mecanum_controller/cmd_vel"
  ros_type_name: "geometry_msgs/msg/TwistStamped"
  gz_type_name: "gz.msgs.Twist"
  direction: ROS_TO_GZ
  lazy: false


