controller_manager:
  ros__parameters:
    update_rate: 100 # Hz
    use_sim_time: true

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    # simple_velocity_controller:
    #   type: velocity_controllers/JointGroupVelocityController

    mecanum_controller:
      type: mecanum_drive_controller/MecanumDriveController  


mecanum_controller:
  ros__parameters:

    # Safety
    reference_timeout: 0.5

    front_left_wheel_command_joint_name: front_left_wheel_joint
    front_right_wheel_command_joint_name: front_right_wheel_joint
    rear_left_wheel_command_joint_name: back_left_wheel_joint
    rear_right_wheel_command_joint_name: back_right_wheel_joint


    # Kinematics
    kinematics:
      wheels_radius: 0.05


      # lx + ly
      # lx = wheel_separation_x / 2
      # ly = wheel_separation_y / 2
      sum_of_robot_center_projection_on_X_Y_axis: 0.47221

    # TF
    base_frame_id: base_footprint
    odom_frame_id: odom
    enable_odom_tf: true 
    open_loop: false
    publish_rate: 50.0
    



    # Covariance (important for EKF / Nav2)
    pose_covariance_diagonal: [0.1, 0.1, 99999.0, 99999.0, 99999.0, 0.2]
    twist_covariance_diagonal: [0.05, 0.05, 99999.0, 99999.0, 99999.0, 0.1]

# simple_velocity_controller:
#  ros__parameters:
#    joints:
#      - front_left_wheel_joint
#      - front_right_wheel_joint
#      - rear_left_wheel_joint
#      - rear_right_wheel_joint
      
      
    

