controller_manager:
  ros__parameters:
    update_rate: 100 # Hz
    use_sim_time: true

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster


    mecanum_controller:
      type: mecanum_drive_controller/MecanumDriveController  


mecanum_controller:
  ros__parameters:

    # Safety
    reference_timeout: 0.5

    front_left_wheel_command_joint_name: front_left_wheel_joint
    front_right_wheel_command_joint_name: front_right_wheel_joint
    rear_left_wheel_command_joint_name: back_left_wheel_joint
    rear_right_wheel_command_joint_name: back_right_wheel_joint


    # Kinematics
    kinematics:
      wheels_radius: 0.05


      # lx + ly
      # lx = wheel_separation_x / 2
      # ly = wheel_separation_y / 2
      sum_of_robot_center_projection_on_X_Y_axis: 0.47221

    # TF
    base_frame_id: base_footprint
    odom_frame_id: odom
    enable_odom_tf: true 
    open_loop: false
    publish_rate: 50.0
    



  


    

